### ISSUE TITLE
Spring boot integration

### ISSUE THREAD

**Issue by qwertukg** [naturalprogrammer/spring-lemon#16]
Is Spring Boot have some planes about integration of Spring Lemon?
And about Kotlin, could i use it with my Kotlin Spring Boot App?

**Comment by naturalprogrammer** [comment]
Just include Spring Lemon dependency in a Spring Boot application, and it works. Look at the getting started guide for details.

We haven't tried with Kotlin, but it should work.

**Comment by qwertukg** [comment]
> Just include Spring Lemon dependency in a Spring Boot application, and it works. 

I mean maybe u now in some conversation with Spring devrlopers about including it into. It will be cool if will be possible to have it in spring from a box, and i can choose it form [start.spring.io](http://start.spring.io/). Cose some customers wanna use only officially spring boot features.

**Comment by naturalprogrammer** [comment]
That's a great idea to pursue. Would require some planning and effort, though. Our first focus is to popularize it, by doing some blogging etc., so that we get more users and possibly a few committers, after which your suggestion would be easier to target.

**Comment by qwertukg** [comment]
nice plan! (bow)
also i gues u should think about including something for tests into your project)

**Comment by naturalprogrammer** [comment]
We're using the [Lemon Demo](https://github.com/naturalprogrammer/lemon-demo) project for doing thorough API testing using Spring MVC tests. We should code some unit tests in this project itself when we have some bandwidth, though. Would be keen to hear if you have some other ideas on testing (or anything in fact)!
