### ISSUE TITLE
LemonTokenAuthenticationFilter invalid implementation

### ISSUE THREAD

**Issue by mmaask** [naturalprogrammer/spring-lemon#24]
The implementation of LemonTokenAuthenticationFilter is not correct. In stateless application you should not use AuthenticationManager to authenticate user on every request. User already authenticated himself through the authentication provider once they first logged in and generated JWT token. Correct filter should build an authentication token from parsed JWT from the request header.

Calling authenticate sends a successful authentication event on success, which is used to save security audit (AuthenticationEventPublisher). Your filter currently would log as many successful authentication log messages as there were requests.

**Comment by naturalprogrammer** [comment]
Good point, Vaelyr. In fact, in early versions of Spring Lemon I had it exactly as you suggest. But I wasn't sure what's the best practice, and thought it's actually authentication, and so might be ideal to actually call the authentication manager and hence publish all the events. Yes, it'll publish the events at each request, which is unnecessary in my opinion too.

I'm willing to change it back, but first like to be sure it's the best practice and later again someone wouldn't want the event raised. So, you sure it's the best practice? Should we first post here some link to some supporting article or document, or I just go changing it -- what do you think?

**Comment by mmaask** [comment]
There is no another alternative to it. Any example you would find for JWT filters do exactly that. The authentication manager is meant for initial authentication only. Every example implementation follows that practice:

1) https://github.com/jhipster/jhipster-sample-app-react/blob/099d281bfa4e5bd20ed3c037fb6766a9b5e9d069/src/main/java/io/github/jhipster/sample/security/jwt/JWTFilter.java
2) JwtTokenFilter section: https://medium.com/@xoor/jwt-authentication-service-44658409e12c
3) The Authorization Filter section: https://auth0.com/blog/implementing-jwt-authentication-on-spring-boot/

And many more

**Comment by naturalprogrammer** [comment]
So, here is the commit: https://github.com/naturalprogrammer/spring-lemon/commit/2b4e97b58f74b444ff80c7d4c3b3cf05bd509c7f

Thanks a lot for this important feedback!
