### ISSUE TITLE
Issue adding updateUserFields in service class.

### ISSUE THREAD

**Issue by NaveenMetta** [naturalprogrammer/spring-lemon#25]
Description	Resource	Path	Location	Type
The type UserDto is not generic; it cannot be parameterized with arguments <Long>	MatapaService.java	/matapa/src/main/java/mahi/tanvi/pandu	line 48	Java Problem

**Comment by naturalprogrammer** [comment]
Couldn't understand the issue. Did you try to refer to the sample https://github.com/naturalprogrammer/spring-lemon/blob/master/lemon-demo-jpa/src/main/java/com/naturalprogrammer/spring/lemondemo/services/MyService.java ?

**Comment by NaveenMetta** [comment]
after adding below method. Also I removed "< Long >". it's complied fine. Test it now. 

![image](https://user-images.githubusercontent.com/17093504/46686152-051f6080-cbbd-11e8-9e79-6ebc13495fce.png)

**Comment by naturalprogrammer** [comment]
Oh, that was a bug in the getting started guide. Fixed. Thank you!
