### ISSUE TITLE
Facebook OAuth not returning expected  'email_verified' attribute

### ISSUE THREAD

**Issue by BWagener** [naturalprogrammer/spring-lemon#26]
I've been trying to implement Spring Lemon into a project. However, when trying authentication through facebook there doesn't seem to be a 'verified' attribute in the response.
As a consequence, a null pointer is thrown in the LemonService class:
java.lang.NullPointerException: null
	at com.naturalprogrammer.spring.lemon.LemonService.getOAuth2AccountVerified(LemonService.java:703) ~[spring-lemon-jpa-1.0.0.M8.jar:1.0.0.M8]

Other attributes such as name, email and id are returned by the facebook provider just fine.

**Comment by naturalprogrammer** [comment]
Thanks for reporting. I'll take a look and try to fix it in the next release, due after a few days. Until then, you could probably override the method in your code?

**Comment by BWagener** [comment]
According to this thread on stackoverflow the graph API only returns verified emails:
https://stackoverflow.com/questions/14280535/is-it-possible-to-check-if-an-email-is-confirmed-on-facebook

Note that the post is rather old though.

**Comment by naturalprogrammer** [comment]
I just checked, facebook does return a `verified` attribute in my case. Did you miss appending `,verified` to the _user-info-uri_, as depicted [here](https://github.com/naturalprogrammer/spring-lemon/wiki/Getting-Started-With-Spring-Lemon#setting-up-applicationyml)?

**Comment by BWagener** [comment]
Thank you for checking. That's odd, I took that part of the configuration as is from the link you provided. Other fields except verified are supplied. 

If you have any advice on how to get to the bottom of this I'd be happy to hear it.

**Comment by BWagener** [comment]
Another issue I've been having which stems from my inexperience is referencing users in other objects.

Say I have an object which was created by a user and I want to persist who created it. I've given the entity a user field which I fill during its creation (part of a service).
Currently I'm grabbing the user using the LecwUtils.currentUser() method.
However, to persist the user as the objects creator I need a User object. What I've done is use the information from the UserDto to get the User object using the lemonService.getUserByEmail() method.
Upon attempting to persist the object created by the user, Hibernate notices the user object has been changed and attempts to persist that. However, the user password has been set to null (as a result of the hideConfidentialFields() I imagine) so the update fails. 

I know this is not an issue with spring lemon. I found a hacky solution and just feel like there has to be a cleaner way for me to achieve this use case (which is probably common - saving objects which reference users I mean)

**Comment by BWagener** [comment]
I've tested whether the configuration I make for facebook.user-info-uri is applied.
https://imgur.com/a/ejNgbQ9
There you can see the LemonService getOAuth2AccountVerified() methods parameters, once with name as part of the facebook.user-info-uri string and once without. So when I remove the name attribute, it also doesn't show up in the attribute map. However the verified attribute never shows up.

**Comment by naturalprogrammer** [comment]
Strange. Maybe Facebook is behaving differently for new users/apps. Anyway, I just changed the method to return false in case of any errors (will release in a few hours). If Facebook only returns verified users, you may need to override the method to return `true`.

For retrieving the current user from database, you could straightly use the `userRepository`. Also note that, in UserDto there's an `id` field as well, which you could use directly or to fetch a user by id from database.

Actually, for storing auditing data, you could just inherit your entity from LemonEntity<ID> instead of doing it manually, and Spring Data Auditing will do it for you.

**Comment by BWagener** [comment]
Thank you so much for your help! I'll definitely dive deeper into the possibilities offered by Spring Lemon, I'm loving it so far! If you're interested in the type of project I'm using it for, check it out at https://playquorum.com - a social game to play with friends IRL.

**Comment by naturalprogrammer** [comment]
Welcome. 1.0.0.M9 released. Also, [documentation](https://github.com/naturalprogrammer/spring-lemon/wiki) being added gradually  – which can be referred to, to take full benefit of Spring Lemon.

And, do post at stackoverflow with `spring-lemon` tag whenever there are questions.
