### ISSUE TITLE
Configure Jacoco or some code coverage plugin

### ISSUE THREAD

**Issue by naturalprogrammer** [naturalprogrammer/spring-lemon#27]
Configure [Jacoco plugin](https://www.baeldung.com/jacoco) in lemon-demo-jpa and lemon-demo-reactive projects.

**Comment by ilyastuit** [comment]
Why I can't find my commit from previous PR in 1.0. I need jacacoVersion from this commit, but it does not exist.
![2021-09-06_15-24](https://user-images.githubusercontent.com/44961501/132203345-a9ab4800-f2ab-416e-b9f6-ae42bcdebef1.png)

**Comment by naturalprogrammer** [comment]
It's there: https://github.com/naturalprogrammer/spring-lemon/commits/1.0
You may need to update your local branch?
