### ISSUE TITLE
How to add more roles?

### ISSUE THREAD

**Issue by jcheros** [naturalprogrammer/spring-lemon#28]
Hi!
I have seen the `Role` interface in `com.naturalprogrammer.spring.lemon.commons.security.UserDto.UserUtils`, I would like to be able to add more roles or customize the interface.

What could I do?

A hug!

**Comment by naturalprogrammer** [comment]
Roles are nothing but strings. Just define more of those as constants in one of your classes, say in your User class.

To you too!

**Comment by jcheros** [comment]
But validations are made based on the ADMIN role, I need to use ADMINISTRATOR instead of ADMIN :-)

**Comment by naturalprogrammer** [comment]
That wouldn't be easy, if somehow possible. But, why do you need to use ADMINISTRATOR instead of ADMIN? It's internal to your application, and shouldn't matter in general, right?

**Comment by naturalprogrammer** [comment]
No capacity to fix this in foreseeable future. So, closing it.
