### ISSUE TITLE
Custom redirect url stopped working

### ISSUE THREAD

**Issue by BWagener** [naturalprogrammer/spring-lemon#29]
Unfortunately custom redirects stopped working for me.
I'm no longer able to do custom redirects like this:
GET /oauth2/authorization/google?lemon_redirect_uri=http://your-front-end-app-url/dynamic-social-login-success?token=

The cookie is being set correctly in the browser.
I'm currently on the RC1 release.

**Comment by naturalprogrammer** [comment]
Have you tried the sample application?

**Comment by BWagener** [comment]
I will try asap. I'm experiencing a few issues with the latest versions of Spring Boot and Spring Lemon unfortunately. It might be specific to my application of course, I'll have to figure that out. 

Besides the dynamic return URL not working anymore the oddest problem is that Google OAuth stopped working for my deployed application while it still works locally. It used to work on older versions of Spring Boot / Lemon.

**Comment by naturalprogrammer** [comment]
> Google OAuth stopped working for my deployed application while it still works locally. It used to work on older versions of Spring Boot / Lemon.

Did you change domain name or something? In Google console you have your key set for your domain?

**Comment by BWagener** [comment]
Everything is the same regarding the domain. I've tried understanding where in the process the authentication fails.

I'm being redirected to Google, select an account to authenticate with and am redirected back to the site running Spring Lemon. In the URL there are parameters set by google ('state' and some more). Looking at the network log the application then returns 401 for the authentication request at the following URL:
https://playquorum.com/login/oauth2/code/google?state=GPa5P3OpT4b4howvFraPm22ZCyCEsc4BavdpicM12Hc%3D&code=4/5ADFuMxvFn1iEEu62iT5W-6nqjefmVx7SQEyUwF3r4jdbX3Z22FuLECBOiD9Dbm6cCCx6UftPw_xOryja1SpUME&scope=openid+email+profile+https://www.googleapis.com/auth/plus.me+https://www.googleapis.com/auth/userinfo.profile+https://www.googleapis.com/auth/userinfo.email&authuser=0&session_state=6bf31b267d2abd0c4435498288155375555e0cfa..8759&prompt=none

It's hard to tell what exactly is going wrong with the authentication since I can't debug remotely and even with log level set to debug there's nothing in the application log about it. 

I've also tried it with new Google OAuth credentials for the application.

**Comment by naturalprogrammer** [comment]
I think I found the cause of custom redirect url stopped working after RC1. Am onto fixing it. Possibly will make another release in a day or two. Thanks for reporting!

**Comment by naturalprogrammer** [comment]
So, 1.0.0.RC2 just released, with the above fix. Could you please try it and see if you face any issues?

**Comment by BWagener** [comment]
I've just tried it locally and the dynamic URL redirect works again. Thank you for the quick fix!
As for OAuth2 with google - considering it's working locally, just not remotely, it's most likely an issue on my end and not related to Spring Lemon.

Cheers

**Comment by BWagener** [comment]
In the process of trying to figure out why OAuth2 with google stopped working when the application is deployed I powercycled the server the application is deployed on. Now it's working again.
