### ISSUE TITLE
Adding parameters for login

### ISSUE THREAD

**Issue by abhinavpawar93** [naturalprogrammer/spring-lemon#31]
Hello
First of all thanks for the awesome library.
Please help me in adding or updating parameters for login. I have read about custom login pages. I can't seem to understand how to do that here. 

Thanks
Abhinav

**Comment by naturalprogrammer** [comment]
Hi Abhinav,

You'll need to receive the parameters in your FrontEnd application and then call the login endpoint. See the AngularJS demo as an example.
