### ISSUE TITLE
no sample working

### ISSUE THREAD

**Issue by sakibulhasan** [naturalprogrammer/spring-lemon#32]
Hello, I really like what you are trying to do in this project but unfortunately, I could not manage to run any of the application. Neither the JPA one nor the reactive one. Is it possible that you make a standalone project (not modular) which just start running with mvn spring-boot: run command? I would highly appreciate that. Thanks.

**Comment by sakibulhasan** [comment]
error in reactive one ......................
[ERROR] Failed to execute goal org.springframework.boot:spring-boot-maven-plugin:2.1.2.RELEASE:run (default-cli) on project spring-lemon-reactive: Unable to find a suitable main class, please add a 'mainClass' property -> [Help 1]
[ERROR]
[ERROR] To see the full stack trace of the errors, re-run Maven with the -e switch.
[ERROR] Re-run Maven using the -X switch to enable full debug logging.
[ERROR]
[ERROR] For more information about the errors and possible solutions, please read the following articles:
[ERROR] [Help 1] http://cwiki.apache.org/confluence/display/MAVEN/MojoExecutionException

**Comment by sakibulhasan** [comment]
I managed to run the reactive demo. Now My question is how do I write my Own controller which is part of the resource server using this as auth serverÉ is there any sample available?

**Comment by naturalprogrammer** [comment]
Hi, there are links to some demo applications and microservices in the home page here: https://github.com/naturalprogrammer/spring-lemon . E.g., there is this link, https://github.com/naturalprogrammer/np-microservices-sample-02 , which you could be looking for.
