### ISSUE TITLE
Device Go offline after connecting initially

### ISSUE THREAD

**Issue by iyushaw** [naturalprogrammer/spring-lemon#39]
I created a host on google cloud to test the system, everything works fine until the client connects and the it gets disconnected and goes offline. I have no idea why it does that or maybe google is doing deep packet inspection and dropping the packets for l3mon.

I also observed there is no means to trouble shoot your connected devices and see if its from the client or the server. also there is no means to delete added clients

![Screenshot from 2020-06-30 12-12-27](https://user-images.githubusercontent.com/858755/86125274-e6b57300-bacb-11ea-8c95-61e358627f88.png)
![Screenshot from 2020-06-30 12-12-51](https://user-images.githubusercontent.com/858755/86125277-e7e6a000-bacb-11ea-9492-99899c345f11.png)

**Comment by naturalprogrammer** [comment]
spring-lemon is basically a stateless API, no previous connection is remembered. So, there may be some other cause for it. So, looks like the mentioned problem is out of scope of spring-lemon project, and I have no knowledge in this area.

**Comment by iyushaw** [comment]
ok... thanks

**Comment by abhishek-sonwani** [comment]
Pleas give me solution for this problem

**Comment by naturalprogrammer** [comment]
I've no clue about this. Yuo could try asking at stackoverflow or somewhere to grab attention of people knowledgeable in these areas.

**Comment by miguelrodriguezpro** [comment]
Same Issue here...

**Comment by brinithkrishna** [comment]
Same issue , anybody know to solve ?
