### ISSUE TITLE
Need to extend SimpleUrlAuthenticationFailureHandler

### ISSUE THREAD

**Issue by havinhphu188** [naturalprogrammer/spring-lemon#41]
.failureHandler(new SimpleUrlAuthenticationFailureHandler()) no longer return JSON. Instead, it return a html page. 

Try a post to /api/core/login with wrong credential return a HTML instead of JSON

LemonAuthenticationFailureHandler need to be implemented

**Comment by naturalprogrammer** [comment]
We have a test case in the `lemon-jpa-demo` project in the source:

``` java
	@Test
	void testLoginWrongPassword() throws Exception {
		
		mvc.perform(post("/api/core/login")
                .param("username", ADMIN_EMAIL)
                .param("password", "wrong-password")
                .header("contentType",  MediaType.APPLICATION_FORM_URLENCODED))
                .andExpect(status().is(401));
	}
```
I tried to add `.andExpect(content().string("xxx"))` and the following came up in the log:

```
MockHttpServletResponse:
           Status = 401
    Error message = Unauthorized
          Headers = [Vary:"Origin", "Access-Control-Request-Method", "Access-Control-Request-Headers", X-Content-Type-Options:"nosniff", X-XSS-Protection:"1; mode=block", Cache-Control:"no-cache, no-store, max-age=0, must-revalidate", Pragma:"no-cache", Expires:"0", X-Frame-Options:"DENY"]
     Content type = null
             Body = 
    Forwarded URL = null
   Redirected URL = null
          Cookies = []
```

Above shows that body is blank, and status is 401. Hence, at first look it seems like it was nither returning JSON nor now it returns HTML.

So, when you say "no longer return JSON. Instead, it return a html page ...," do you mean it behaves differently in real environments, and previously it was returning JSON and now it retuens HTML? Could you please try it from a tool like cURL or Postman and share your findings?

**Comment by havinhphu188** [comment]
Hi @naturalprogrammer, 
Here is what I am doing:
1. I am trying to demo lemon-demo-jpa project. 
2. I start lemon-demo-jpa as a normal spring-boot apps
3. I found postman script inside directory "spring-lemon\lemon-demo-jpa\src\test\resources\postman" .
![image](https://user-images.githubusercontent.com/16551722/107518120-3b33db80-6be1-11eb-8096-9c738cf57c97.png)

4. I import the postman scripts.
5. I found post login, with examples:
6. I assume the login failed is expecting JSON response
![image](https://user-images.githubusercontent.com/16551722/107517220-0bd09f00-6be0-11eb-825e-ab54527e3f20.png)

7. I try out Post login with correct credential (according to provided e.g). => success login return JSON result, as expected. Nothing to complain
8. THen, I try out Post login with false credential, it return status 401 with HTML body
9. 
![image](https://user-images.githubusercontent.com/16551722/107517702-aa5d0000-6be0-11eb-8d57-a4fd9bdfe41a.png)



P/S: Number 6 is what I assume expected behavior, according to provided Postman script. Number 9 is what I found in reality.
And when look into code, I find no implementation to extend SimpleUrlAuthenticationFailureHandler

**Comment by naturalprogrammer** [comment]
Okay, I'd try to reproduce it. BTW, it'd be very helpful if you could try from cURL, or you could try running the angularjs project (see the getting started guide for details) and test it out. I'm suspecting that, because there's no body, there is no content type, and so Postmen is defaulting to showing some HTML.

**Comment by naturalprogrammer** [comment]
Thanks for catching it, and for the elaborated input! Looks like, Spring Boot 2.4 onwards, `DefaultErrorAttributes`'s `getErrorgetError(WebRequest webRequest)` returns `null`, which was causing null pointer exception in `LexUtils.getRootException(Throwable ex)`. Fixed in 2307248acb5180b95f68c69bba43727db3f703fa, would be released along with 1.0.0.RC7.

**Comment by neelimaJ026832** [comment]
Hi @naturalprogrammer, Is it possible to do spring impersonation with different domain URLs? For example Admin website URL domain (which uses LDAP authentication) is different from Customer website URL domain (which uses form based authentication).

**Comment by naturalprogrammer** [comment]
Couldn't follow your question exactly. If your question is that if you could use the lemon authentication token for both websites -- should work. Unrelted to this ticket, though. Or maybe I don't understand your question. Would be nice if you could elaborate it.

**Comment by naturalprogrammer** [comment]
Fix released: https://github.com/naturalprogrammer/spring-lemon/releases/tag/1.0.1
