### ISSUE TITLE
Broken image link in Spring Lemon Exceptions guide

### ISSUE THREAD

**Issue by asarkar** [naturalprogrammer/spring-lemon#42]
https://github.com/naturalprogrammer/spring-lemon/wiki/Spring-Lemon-Exceptions-Guide#coding-exception-handlers

> Spring Lemon already comes with a rich set of exception handlers:

Spring Lemon exception handler hierarchy <--- Broken link

**Comment by naturalprogrammer** [comment]
Thanks for pointing out. Fixed.

**Comment by asarkar** [comment]
I think a direct link to the package containing the classes shown is more likely to withstand the test of time than a screenshot.

**Comment by naturalprogrammer** [comment]
They are in different packages. But if one'd check out the source, one could just open the base class and use the IDE to see the heirarchy.
