### ISSUE TITLE
Non existent Maven repo in the Spring-Lemon documentation

### ISSUE THREAD

**Issue by asarkar** [naturalprogrammer/spring-lemon#43]
spring-lemon-exceptions isn't published in Maven Central (why not?). There's an SO question about this in 2016 https://stackoverflow.com/q/36316717/839733.
The Maven repo shown in the docs returns 404.
https://github.com/naturalprogrammer/spring-lemon/wiki/Spring-Lemon-Exceptions-Guide#adding-to-your-spring-boot-project
```
<repositories>

    <repository>
        <id>naturalprogrammer</id>
        <url>https://naturalprogrammer.github.io/mvn-repository</url>
    </repository>
    ...
</repositories>
```

Makes me question whether there is a serious commitment to maintaining this project, or it's just someone's weekend project.

**Comment by naturalprogrammer** [comment]
I tested that the getting started guide works. Local mavne repositiry is populated with spring-lemon arctfcts when you incluse the reop. Is the getting started guide not working for you?

You're right, although I'm serious about the project, this is a kinda weekend project so far. I didn't feel the priority yet of publishing it to maven central, but thanks for the reminder, let me pop up this in my list.

**Comment by asarkar** [comment]
What do you see if you enter [the URL](https://naturalprogrammer.github.io/mvn-repository) in a browser? As I mentioned in my ticket, I get a 404. For a build tool to be able to resolve it as a Maven repo, it should be set up as one.
Regarding the support, I think the number of forks is a good indicator that people aren’t getting the support they’re looking for, and simply starting their own.

**Comment by naturalprogrammer** [comment]
> What do you see if you enter the URL in a browser?

404

> For a build tool to be able to resolve it as a Maven repo, it should be set up as one.

Not sure if I get it right -- do you face issues when you follow the getting started tutorial?

**Comment by asarkar** [comment]
> do you face issues when you follow the getting started tutorial?

Yes, as I said twice thus far. Nothing is downloaded, and given the 404, I don’t see how it’s supposed to work.

**Comment by naturalprogrammer** [comment]
I don't think getting 404 when trying to browse https://naturalprogrammer.github.io/mvn-repository would imply that maven can't pull the files. E.g. https://naturalprogrammer.github.io/mvn-repository/com/naturalprogrammer/spring-lemon/spring-lemon-exceptions/1.0.0.RC5/spring-lemon-exceptions-1.0.0.RC5.jar doesn't get me 404.

As I said, as per my test, maven should be able to pull the artifacts. If that's not happening in you case, I think it might help if you delete com/naturalprogrammer folder in your local maven repository and retry.

(And of course, I totally agree that getting the artifacts to maven central is definitely  good idea and is on my list.)

**Comment by naturalprogrammer** [comment]
1.0.0.RC6 onward now available on maven central
