### ISSUE TITLE
I want to use the spring lemon exceptions module in my project. How can I introduce it?

### ISSUE THREAD

**Issue by baiyifengyun** [naturalprogrammer/spring-lemon#49]
org.springframework.beans.factory.BeanCreationException: Error creating bean with name 'lexUtils': Invocation of init method failed; nested exception is org.springframework.context.NoSuchMessageException: No message found under code 'com.naturalprogrammer.spring.notFound' for locale 'zh_CN'.

**Comment by naturalprogrammer** [comment]
You'd have to have create a `messages.properties` inside `src\main\resources` if you haven't done it already, and paste the following into that:
```
com.naturalprogrammer.spring.notFound: Not found
```
Hopefully it works.
